### ISSUE TITLE
Dual screen setups?

### ISSUE THREAD

**Issue by beanfarmer** [icedman/dash2dock-lite#1]
![Screenshot from 2022-04-15 17-09-26](https://user-images.githubusercontent.com/3500952/163594209-d9fb2a23-3cda-488e-b3b4-4bb9099d729b.png)

Seems like there's an issue with dual screen setups the dock is going to the center of both screens rather than the center of the main display.

**Comment by icedman** [comment]
I've added support for multi-monitor with the last commit.

**Comment by Mladia** [comment]
It doesn't seem to work, at least in my case. Can someone else confirm this as well?

**Comment by andohuman** [comment]
It works normally on my main screen but my second monitor doesn't have any dock.

**Comment by icedman** [comment]
davidzambo's branch feature/primary_monitor_handling was recently merged. works pretty well on my tests.

The dock only shows at the primary monitor.
