### ISSUE TITLE
BUG: (Fixed - For tests) does not work in the latest version of gnome 46

### ISSUE THREAD

**Issue by alvarorichard** [icedman/dash2dock-lite#101]
![image](https://github.com/icedman/dash2dock-lite/assets/88117897/b7d0ab5f-9022-4ace-814b-92bbe908a77e)

**Comment by icedman** [comment]
see issue #98 
Please test the development branch. Or the g46 branch.

**Comment by alvarorichard** [comment]
ok thanks
