### ISSUE TITLE
BUG: Sensitivity issue with window cycling

### ISSUE THREAD

**Issue by joshqou** [icedman/dash2dock-lite#103]
Originally [icedman/anino-dock#6](https://github.com/icedman/anino-dock/issues/6):
> Even on the highest sensitivity, Anino doesn't seem to detect small scroll wheel up or down movements. I have to scroll at least 5 positions on my mouse for Anino to register that I've scrolled up or down. This issue also effects Dash to Dock Lite
> 
> Changing my mouse resolution or refresh rate in Piper doesn't seem to help.

The sensitivity setting may be capped too low as even the smallest scroll can raise a hidden app, but multiple are required to switch between windows.

**Comment by icedman** [comment]
Added both touchpad and scroll wheel support. Todo: the sensitivity values has the opposite effect.

**Comment by icedman** [comment]
Todo: add more range to sensitivity settings.

**Comment by icedman** [comment]
settings for sensitivity has been recently added

**Comment by joshqou** [comment]
Sensitivity is much better now, however the switching grace period is a bit too high for me. Does it not scale with the sensitivity?

**Comment by icedman** [comment]
Currently it is fixed at half second.
