### ISSUE TITLE
Incompatible with just perfect extension's position of clock settings

### ISSUE THREAD

**Issue by ilsubyeega** [icedman/dash2dock-lite#109]
[Screencast from 2024-03-29 18-17-29.webm](https://github.com/icedman/dash2dock-lite/assets/37479424/e0946234-8327-456b-aa15-6e617a76a0ba)

If you change the clock position of the gnome top bar in just perfection, dash2dock-lite will throw an error. It's not shown in the video, but if you restart the extension from there, it doesn't start and show docks.

Based on: arch, gnome 46, latest commit with make

**Comment by icedman** [comment]
Thanks for the catch.

**Comment by ilsubyeega** [comment]
Yep, that commit fixed the issue, thank you for developing extension!
