### ISSUE TITLE
[Request] Put this extension on extensions.gnome.org or provide a compiled zip in github releases

### ISSUE THREAD

**Issue by afland** [icedman/dash2dock-lite#11]
I realize this extension is more of a thing you're maintaining for yourself on the side, but it would be great if you could submit it to extensions.gnome.org or provide a compiled zip. I'm running Fedora Silverblue, so it's difficult to compile anything myself with `make`, and I'd rather stay away from that if possible.

**Comment by icedman** [comment]
dash2dock-lite is already at extensions.gnome.org. It is also at the AUR repository - maintained by one of our contributors. I've been planning on also publishing as a snap, but I haven't setup and ubuntu system yet.
