### ISSUE TITLE
Dash icons are huge

### ISSUE THREAD

**Issue by grgendron** [icedman/dash2dock-lite#114]
Your build/version: 54
Me: Fedora 40 beta (Gnome 46), fractional scaling enabled and set to 1.5 on a 2560 x 1600 screen.
The icons in the dash are huge, even when settings set to minimal size. This screenshot seems to minimize the 'hugeness' of what I am seeing on my screen:

![Screenshot from 2024-04-02 13-07-12](https://github.com/icedman/dash2dock-lite/assets/7870326/a6a492f4-a4ee-4b8f-bf98-32c83e90c4ae)

**Comment by icedman** [comment]
For some forgotten reason, I multiplied the preferred icon size to 2. I will need to revamp the icon sizing.
```js
iconSize =
        2 *
        (preferredIconSizes[
          Math.floor(this.extension.icon_size * preferredIconSizes.length)
        ] || 64);
      iconSize *= this.extension.scale;
```
