### ISSUE TITLE
download folder expand style weird

### ISSUE THREAD

**Issue by MarsSwimmer** [icedman/dash2dock-lite#117]
Download folder expand show weird, like this:
![截图 2024-04-05 01-03-59](https://github.com/icedman/dash2dock-lite/assets/146618222/651675d0-649d-4476-8ad6-e06dcc14d0d8)

expected like introduce image:
![Screenshot from 2024-03-19 15-31-27](https://github.com/icedman/dash2dock-lite/assets/146618222/725c8e58-0272-4551-9a36-1d8ce2c28655)

my os info:
- Ubuntu 23.10
- Gnome version: 45.2
- Display Scale 2.0
- X11 and Wayland can see the style bug

dash2dock-light version:
- 54, download from https://extensions.gnome.org/, can see the style bug
- download from github branch main use make to install, it show too
- download from github branch develop use make to install, it show too
- download from github branch code-review use make to install, it show too

I really like dash2dock-light, hope it can be fixed,

Best regard!

**Comment by icedman** [comment]
I added to settings to angle the pullout angle.  Tweaks > Items Angle

**Comment by icedman** [comment]
The computation is just an arc.  The increment is 0.5-2 degrees per item. Previous computation has been changed due to problems with 2x scaled display.

**Comment by icedman** [comment]
I can probably adjust a little the curve to linearly increase.

**Comment by MarsSwimmer** [comment]
Thank you for you reply,

Now the expand style is perfect, I have pull development branch and install it.
![截图 2024-04-05 22-54-10](https://github.com/icedman/dash2dock-lite/assets/146618222/3833c823-5cb4-4d44-ae73-fbb33ad4c45d)


But there is still another bug, in x11 environment, click icon doesnt work, cant open app window, and cant expand download folders, the bug show frequently, and sometime show on wayland.

Best regards !

**Comment by MarsSwimmer** [comment]
Addtional, if click a icon so many times, block dock bug will show, cant open app, and cant expand download folders, cant show overval, x11 environment.

**Comment by icedman** [comment]
> Addtional, if click a icon so many times, block dock bug will show, cant open app, and cant expand download folders, cant show overval, x11 environment.

Yes, I see this also. Fixed a few moments ago.
I haven't been checking x11 yet though.

**Comment by icedman** [comment]
I pushed a fix for X11.
