### ISSUE TITLE
Displaying in 60fps

### ISSUE THREAD

**Issue by Maciejka1** [icedman/dash2dock-lite#12]
Hey, I have 180hz monitor and this extension looks like it's displayed in 60fps or less.

**Comment by icedman** [comment]
Animation update is called every 25ms. 40ps? I'll probably make this adjustible. 
While in animation the cpu usage of gnome-shell spikes up.
The current animation moves icon around or updates their positions rather than drawing them more efficiently on a graphics canvas.
