### ISSUE TITLE
RDP session bug

### ISSUE THREAD

**Issue by Aqua1ung** [icedman/dash2dock-lite#124]
[Here's a video](https://photos.app.goo.gl/RfWTFkcmmUU1Bgte7) of another bug that happens during an RDP session: upon launching an RDP session, the dock on the remote desktop fails to show up ... unless one proceeds at disabling the extension, and re-enabling it back.

**Comment by icedman** [comment]
Works fine also if the desktop is already logged in. Is it possible for you to check the logs for errors?

**Comment by Aqua1ung** [comment]
Yes, if the desktop is already logged in, everything is fine. This happens only when one launches a brand new GNOME session via RDP.

I will check the logs and report back.

**Comment by Aqua1ung** [comment]
Looks like 64 fixes this.
