### ISSUE TITLE
Gio.IOErrorEnum bug

### ISSUE THREAD

**Issue by Aqua1ung** [icedman/dash2dock-lite#125]
Here's a screenshot of another bug that's been bugging me lately, though I am not sure how to replicate it. Prima facie, it seems to occur upon unlocking the desktop.

![Screenshot from 2024-04-22 17-39-08](https://github.com/icedman/dash2dock-lite/assets/12104779/8faec5a3-091b-403a-976f-734898a12ca6)

[Edit: attached is a log excerpt that looked to me to be relevant to this.]

[D2DAnimatedBug.txt](https://github.com/icedman/dash2dock-lite/files/15068915/D2DAnimatedBug.txt)

**Comment by icedman** [comment]
From you photo, it looks like root directory is being seem as a mounted device. Not user why that happens. Please try a possible fix that I just pushed.

**Comment by Aqua1ung** [comment]
Hasn't happened lately. Very likely fixed in 64 or 65. Closing.
