### ISSUE TITLE
Move a window to a different workspace

### ISSUE THREAD

**Issue by HollowMoon477** [icedman/dash2dock-lite#126]
[Screencast from 2024-04-24 18-49-18.webm](https://github.com/icedman/dash2dock-lite/assets/104750233/fdf8c517-7497-4473-bbe6-17d5aa338d61)
=================
OS build rolling, Arch 64-bit, Linux 6.8.7-arch1-1, Wayland, gnome 46.

**Comment by HollowMoon477** [comment]
I also disabled all extensions leaving only dash2dock

**Comment by HollowMoon477** [comment]
I also disabled all extensions, leaving only dash2dock, but it did not help

**Comment by icedman** [comment]
Confirmed. I will investigate.
