### ISSUE TITLE
Arc Menu support

### ISSUE THREAD

**Issue by vnagfighter** [icedman/dash2dock-lite#13]
I like gnome but the only thing that not like about it is that it's using a app grid and I would like to have a more "windows" like experience (I used windows I like gnome's layout but I don't like the app grid at all.)

**Comment by icedman** [comment]
I'm currently not inclined to add more features to keep the plugin "lite."
I do have another project call [search-light](https://github.com/icedman/search-light).
It gives a more macos experience - similar to Spotlight, or Alfred. you might want to try it.

**Comment by icedman** [comment]
```I'm currently not inclined to add more features to keep the plugin "lite."``` 
This statement is no longer true. The word "Lite" should probably now be dropped.

Could you explain further this feature request.

**Comment by vnagfighter** [comment]
There are people who doesn't like full screen app grids and with arc menu you can change the "app list".
But it's more for a smaller popup menu to launch app, like pop_os!'s pop-launcher.

**Comment by icedman** [comment]
This feature will be considered under Anino Dock ... https://github.com/icedman/anino-dock
Dash2Dock Lite will try to minimize features and become lightweight again.
