### ISSUE TITLE
Bug: Jerky at Secondary monitor

### ISSUE THREAD

**Issue by icedman** [icedman/dash2dock-lite#130]
There is, however a minor issue with the dock on the secondary monitor: see [this video here](https://photos.app.goo.gl/2s1iWa6n4YQNse9D7). While the dock on the primary monitor is smooth when hovering over the icons, the dock on the secondary monitor is jerky. It appears as if the dock changes its size when one moves from icon to icon.

**Comment by Aqua1ung** [comment]
Version 65 fixes this. Works great! You da man!

Feel free to close this bug please.

**Comment by sjhaleprogrammer** [comment]
This issue reappeared, I got 3 montiors
