### ISSUE TITLE
Bug: no autohide on secondary monitor

### ISSUE THREAD

**Issue by Aqua1ung** [icedman/dash2dock-lite#132]
See title line. GNOME 46, Dash2Dock Animated 64. [Here's the video](https://photos.app.goo.gl/v6iFYKoad5CMGnkd7).

Also note the absence of app indicators (dots) on the primary monitor, and the presence of very tiny app indicators (tiny dots) on the secondary monitor. (Feel free to make another bug about this one.)

**Comment by icedman** [comment]
Autohide should have been fixed along with the jerky screen from yesterday's push. Please pull the latest development branch if you haven't yet.

**Comment by Aqua1ung** [comment]
Thanks. I'd rather wait until you push it to ego. I can't afford the mess of switching between ego installations and Git installations.
