### ISSUE TITLE
Dot, app indicators

### ISSUE THREAD

**Issue by alisson3000br** [icedman/dash2dock-lite#135]
all of the options are the same the indicators are on top of the icons

thanks

![Screenshot from 2024-04-28 19-50-27](https://github.com/icedman/dash2dock-lite/assets/148722558/f2e938f5-4cfe-4533-8fee-7728fb6dfecc)
![Screenshot from 2024-04-28 19-50-36](https://github.com/icedman/dash2dock-lite/assets/148722558/e81bd3fa-8db1-4566-ad1c-e2cedde5d82d)

**Comment by alisson3000br** [comment]
its also very big the indicators

**Comment by not-Boris** [comment]
Also having this issue, disabling "Shrink Icons" and adjusting the icon size fixes this, but it's not a solution.

**Comment by not-Boris** [comment]
Video of Issue:
[Screencast_29_04_24_11:02:37.webm](https://github.com/icedman/dash2dock-lite/assets/61906888/7cc3006d-be9c-49da-ba6f-12b32ff4807f)
As the icon size grows, the app indicators seem to misalign.

**Comment by alisson3000br** [comment]
Even resizing does not fix, well, i congratulate the developer anyways because this is becoming the best dock ever!!!
I hope this is fixed soon

![Screenshot from 2024-04-29 15-23-02](https://github.com/icedman/dash2dock-lite/assets/148722558/eb9740f9-9fd6-42ad-8634-ed65a0d28b17)

**Comment by alisson3000br** [comment]
there is not option to resize the dots, i like very small, dash to dock is very small

**Comment by hachikoharuno** [comment]
After the last update, indicators are not displayed correctly at 2x scale. On 1x everything looks correct. The size of the icons has no effect on this. I also checked the development branch.

![Снимок экрана от 2024-05-05 21-09-55](https://github.com/icedman/dash2dock-lite/assets/86525501/42f59d70-a908-41f9-9598-df7027f3048a)

**Comment by icedman** [comment]
2x scale is such a headache :)

**Comment by alisson3000br** [comment]
Improved a lot with the new options but now the dots are too low, is there a place to edit like stylesheet like dash to dock? in dash to dock stylesheet i manage to edit the dots 
![Screenshot from 2024-05-28 21-44-38](https://github.com/icedman/dash2dock-lite/assets/148722558/ec5d7f31-2a76-4021-bcee-af542a9bf21a)

also the windows are minimizing to the panel not to the dock and the overview showing up only blank with no icons

**Comment by alisson3000br** [comment]
i am using wayland

**Comment by luismxlina** [comment]
Same problem about the x2 resolution here. That also affects the hiding bar animation, as the lower speed, hides the bar in a blink with almost no visual movement. 

This extension is great and these are seamlessly minor problems that if we support more, could be fixed nicely. May there be a plan for these adaptations to be made? Maybe opening different issues for each one? 

 I would like to help if i got introduced a little bit in the codebase and understand how the scaling calculations are made so I can try and fix it :)

**Comment by AntonKrychevskyy** [comment]
I am on Fedora 40 with Wayland. Have built-in laptop screen with 2x scale and two external monitors with 1x scale. 


#### Dots

On external monitors everything looks good probably except that dots not centered properly. 
On built-in monitor they are too small and positioned vertically on the center of icon, and closer to left edge horizontally. 

_2x scale screen dock_
![2x scale screen dock](https://github.com/user-attachments/assets/b453d452-ecb2-4a91-8fac-63fc2c47ee91)

_2x scale screen dock icon hover_
![2x scale screen dock icon hover](https://github.com/user-attachments/assets/6063c52b-e15a-456b-b51e-d6d025102ebd)


#### Edge Distance

There is also inconsistency in dock edge distance on 2x scale and 1x scale monitors. While on 2x scale screen there is a distance between dock bottom edge and screen edge, on the 1x scale dock bottom edge is touching the screen edge. And if I increase edge distance distance so it will have modest distance on 1x scale screen, then on 2x scale screen it will have too big distance.

_1x scale screen dock touch screen edge_
![1x scale screen dock touch screen edge](https://github.com/user-attachments/assets/53acc506-ec5d-45fb-9427-accf13b949c4)

_1x scale screen dock distance fixed_
![1x scale screen dock distance fixed](https://github.com/user-attachments/assets/1093a4e1-1b8c-47dd-82f7-2c87b6d74d13)

_2x scale screen dock distance to big_
![2x scale screen dock distance to big](https://github.com/user-attachments/assets/8e2f0feb-36b3-4805-b41e-2db150a19484)
