### ISSUE TITLE
Bug/Crash Report: Dock disappears permanently and extension manager shows Error "TypeError: stateObj is undefined"

### ISSUE THREAD

**Issue by Nitzgi** [icedman/dash2dock-lite#140]
**Specs:**
![Bildschirmfoto vom 2024-05-09 20-54-22](https://github.com/icedman/dash2dock-lite/assets/147719515/73f4ef5c-134c-485a-aeb1-f20ef00b52ba)
After the PC turns automatically in the standby mode, the dock disappears and can't be returned by turning the extension off and on again in the extension manager.

![Bildschirmfoto vom 2024-05-09 20-45-35](https://github.com/icedman/dash2dock-lite/assets/147719515/6dbb421f-2e92-427a-b6b4-480aa4b5f44e)

The extension manager shows the following: "TypeError: stateObj is undefined"
Maybe some other extensions causes this. For this my installed and activated extensions:

![Bildschirmfoto vom 2024-05-09 20-59-48](https://github.com/icedman/dash2dock-lite/assets/147719515/8fa9b323-0c82-4801-92ec-c5874bdcd8cc)
![Bildschirmfoto vom 2024-05-09 21-00-10](https://github.com/icedman/dash2dock-lite/assets/147719515/6d7103f0-538e-4d6f-a6ab-e37791d3c410)

Rebooting starts the dock again temporarily till the next crash (bug)

Would be delicious if someone could fix this.

A big thank you too for your work already done.

**Comment by icedman** [comment]
Please post log if you can. See README on capturing the log. Thanks!

I'm becoming a little busy these days. But will try to fix bugs over weekends.

**Comment by icedman** [comment]
It looks like the bug is with compatibility with compiz lamp effect : (compiz-alike-magic-lamp-effect@hermes83.github.com)
The d2da incorrectly assumes that the extension is enabled.

Temporary workaround:
1. Enable compiz
2. Or uninstall compiz lamp animation extension for now.

**Comment by Nitzgi** [comment]
Thanks a lot for the ultra fast response and the possible identification of the problem! This is great!

Here I have created a .txt-File of the output of your in the README recommended command for the Bug identification. First i wanted to make a screenshot, but the output became to long.

[output.txt](https://github.com/icedman/dash2dock-lite/files/15272945/output.txt)

If I can do anything for helping you further, just let me know. Since I am a complete Linux newbie, I will not know some things that seem self-evident and will need instructions.

Thanks for your work!

**Comment by Nitzgi** [comment]
Thanks a lot for the ultra fast response and the possible identification of the problem! This is great!

Here I have created a .txt-File of the output of your in the README recommended command for the Bug identification. First i wanted to make a screenshot, but the output became to long.

[output.txt](https://github.com/icedman/dash2dock-lite/files/15272945/output.txt)

If I can do anything for helping you further, just let me know. Since I am a complete Linux newbie, I will not know some things that seem self-evident and will need instructions.

Thanks for your work!
