### ISSUE TITLE
How to implement the preview function as shown in the README screenshot?

### ISSUE THREAD

**Issue by Emore003** [icedman/dash2dock-lite#147]
hi icedman

This GNOME extension is excellent, but I have a question. How did you implement the functionality described in your README? I couldn't find the relevant configuration options in the settings. Could you provide the relevant configuration method?
![PixPin_2024-06-03_15-58-17](https://github.com/icedman/dash2dock-lite/assets/139245324/ba49e22c-a16f-4d17-ba46-f4eaa0b81ef3)

**Comment by Emore003** [comment]
hi Ticklezz

I don't understand very well, I didn't find the relevant setting options in the icons section and what you said "Downloads", can you elaborate on it a little more, or provide a screenshot of the relevant one;
If you need to download an additional download, is there a link to download it; 

thinks.

**Comment by Ticklezz** [comment]
> hi Ticklezz
> 
> I don't understand very well, I didn't find the relevant setting options in the icons section and what you said "Downloads", can you elaborate on it a little more, or provide a screenshot of the relevant one; If you need to download an additional download, is there a link to download it;
> 
> thinks.

![Screenshot from 2024-06-04 05-30-57](https://github.com/icedman/dash2dock-lite/assets/113319295/6be67611-496f-4e19-b40b-e53b1b163560)
Activate downloads button.

**Comment by Emore003** [comment]
Ok, I see, only the downloads button has this effect, other icons can't preview like this, thank you very much

**Comment by Ticklezz** [comment]
> Ok, I see, only the downloads button has this effect, other icons can't preview like this, thank you very much

You should close this to take it off the issues list.

**Comment by Emore003** [comment]
ok，thx
