### ISSUE TITLE
Better actions and gestures

### ISSUE THREAD

**Issue by TheWeirdDev** [icedman/dash2dock-lite#15]
Hi and thanks for the nice work.
Now I can finally move to wayland and replace plank with this extension.

There are only a few features I miss from other docks. Mostly actions and gestures. I'd really appreciate if you add these features in the future:

-  **Click to minimize**
Clicking the minimize button at the top of the window is hard. It would be nice to click the dock icon instead.

- **Scroll to cycle windows**
When you have multiple windows of the same app (maybe in different workspaces), using mouse scroll to cycle between them is very useful

**Comment by icedman** [comment]
These are nice suggestions. But I'm not inclined to add more features to keep the extension "lite".

I have another extension "dash-animator" which animates the "dash to dock (cosmic or ubuntu)". Their dock is more feature rich and my extension merely adds the animation.

The more features though, the more likely it would break at Gnome's major releases - as you may have experienced with large plugins. So the "lite" reminds me to not get tempted add more features. I was lured into adding intellihide :) but maybe that will be it.

**Comment by TheWeirdDev** [comment]
Yes you are right. I'm closing this issue.
