### ISSUE TITLE
Set custom sensitivity area for showing the dock

### ISSUE THREAD

**Issue by TheWeirdDev** [icedman/dash2dock-lite#16]
When I have the dock hidden at the bottom of the screen, it will show up with mouse cursor anywhere near the bottom.

It would be nice to be able to customize the sensitivity area to only show the dock when the cursor is at the bottom center or it is where the dock should be.

Thanks.

**Comment by icedman** [comment]
I added a feature where the "pressure sense" is activated only when you let the mouse dwell on an area at the bottom of the screen. 
You have to move the mouse down - without moving too much horizontally - to trigger the dock to show.
This means if you move the mouse around the screen - even accidentally touching the bottom - the dock won't show.

**Comment by TheWeirdDev** [comment]
Alright that will do. Thanks.
