### ISSUE TITLE
Bug: The bottom of the screen is unclickable

### ISSUE THREAD

**Issue by TheWeirdDev** [icedman/dash2dock-lite#17]
When using this extension the bottom of any maximized app becomes unclickable (around 10-20 pixels). Other extensions like dash-to-dock didn't have this behavior. I'm not sure what's causing it but it seems like the dock doesn't entirely hide away and blocks the mouse click on anything under it.

**Comment by icedman** [comment]
Yes that was by design so that the extension does not need to poll and track position. Instead, it just listens for mouseEnter. I will test with lowering the trigger height.
