### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#19]
- Adjust dash-dock height from screen edge depending upon the position of the dock (top, bottom, left, right)
- Include Trash, mounted volumes, App launcher, and a separator for favorite apps
- Include background selection from current shell theme or other shell themes installed

**Comment by icedman** [comment]
Dynamic trash icon (experimenta)l is at the development branch.

**Comment by icedman** [comment]
Mounted device icons, analog clock & calendar are now in.
