### ISSUE TITLE
Settings/Autohide

### ISSUE THREAD

**Issue by ThatOneCalculator** [icedman/dash2dock-lite#20]
Adding some settings from the original dash to dock like autohide would be great :)

**Comment by icedman** [comment]
This feature will be considered under Anino Dock ... https://github.com/icedman/anino-dock

**Comment by ThatOneCalculator** [comment]
I'm a bit confused -- why do you keep making new projects that are so similar to your past ones rather than just making new releases/possibly renaming them?
