### ISSUE TITLE
animation defect

### ISSUE THREAD

**Issue by Tuxino88** [icedman/dash2dock-lite#21]
the dash "jumps" in the overview

Gnome 43 fedora 37

[Video del 2022-10-18 19-25-30.webm](https://user-images.githubusercontent.com/75674245/196502280-b4b59860-7401-46b8-acf2-02d03f53d84f.webm)

**Comment by Tuxino88** [comment]
NB other issue : when dash is hidden and I go down with mouse to make it appear , it lacks the "slide up" animation typical of dash-to-dock

**Comment by icedman** [comment]
Fixed
