### ISSUE TITLE
4K display - bouncy bug

### ISSUE THREAD

**Issue by icedman** [icedman/dash2dock-lite#22]
"On a 4k screen, when autohide is enabled, the dock sits a third of the way up the screen. Then when hovering, the dock "bounces" quickly between the bottom edge and its original position a third of the way up. Let me know if I can provide a more helpful report than that.

Works well when autohide is disabled."

redditor: [butseriouslythough](https://www.reddit.com/user/butseriouslythough/)

**Comment by Hview911** [comment]
Just wanted to add:
Same thing happened with my extension when i connected a secondary monitor.
My main monitor is a LG Ultrawide 32" with 2560x1080p resolution. Works flawless alone!
Connected a secondary monitor (Standard HP Business monitor) 24" 1920x1080p resolution, and this bug appeared.
Disconnecting the secondary monitor or disable "auto hide" will make the bug go away, even tho this is not optimal.
