### ISSUE TITLE
[Feature Requests] Dash theme

### ISSUE THREAD

**Issue by Tuxino88** [icedman/dash2dock-lite#25]
is possible to modify dash style like MacOs?

![Schermata del 2022-10-19 17-30-11](https://user-images.githubusercontent.com/75674245/196736594-3f1b8a17-1203-4cd1-b7a8-4163d6604cc0.png)

**Comment by icedman** [comment]
This feature will be considered under Anino Dock ... https://github.com/icedman/anino-dock
