### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#26]
Ability to freely add and remove 

1. Running apps from dock
2. Apps icon, Trash icon and other ones
3. Ability to change dock position from screen edge as margin

**Comment by icedman** [comment]
#2 & #3 are in development branch

**Comment by prashantjain25** [comment]
Dock seems stable now, feature "1" could be critical as in a multitasking environment lots of apps fill the dock therefore hiding them could be a must.

**Comment by icedman** [comment]
Add 1. feature request. Still buggy if you change the setting while apps are already running.

**Comment by prashantjain25** [comment]
Success :thumbsup: seems it will be the best dock on Linux :crossed_fingers:
