### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#29]
- It would be nice to have single bounce effect with sound effect(on/off) on application launch as few apps don't respond quickly so one can accidentally click dock icons multiple times.
- It would be nice to have a flexible separator(items movable) to separate trash/system icons from launchers.
- It would be nice to have vertical/horizontal padding option with decimal value for icons on the dock(to make dock icons compact/sparse in place of "shrink option")

**Comment by pallebone** [comment]
Bounce effect would be like this extension reaching its final form. Would be awesome.

**Comment by icedman** [comment]
Bounce effect added

**Comment by pallebone** [comment]
Thank you.

**Comment by prashantjain25** [comment]
Tried development branch bounce effect not happening, cloned everything again  and used script to make.
