### ISSUE TITLE
DOCK takes up the screen in a bad way 

### ISSUE THREAD

**Issue by soorajsprakash** [icedman/dash2dock-lite#3]
1. firefox ![FIREFOX](https://user-images.githubusercontent.com/26853789/163671477-52f96b1d-324c-4c2e-981b-7a79a03a5e0b.png)

2. nautilus ![NAUTILUS](https://user-images.githubusercontent.com/26853789/163671499-0f5f35f8-714d-4969-8ba3-1b5046cccc3c.png)

Anyway to make this look normal?

**Comment by lucasburlingham** [comment]
What exactly is the issue? Are the apps full screen?

**Comment by icedman** [comment]
autohide feature will be added

**Comment by soorajsprakash** [comment]
@lucasburlingham yes apps are full-screen, but our dock won't allow that, dock is not allowing any app to be till the bottom.

And @icedman I don't think that auto-hide will fix the issue, maybe temporarily yes, but when we disable auto-hide, or add a delay for hiding dock, then we can easily see that it shouldn't work like that.

**Comment by icedman** [comment]
That screenshot is how I intended the dock to be. There are many other configurations or layouts that are.notnyet currently.supported. You can suggest one here as a feature request.

**Comment by icedman** [comment]
Intellihide feature would probably not be added to dash2dock lite.

Please see my other project. Dash-Animator

https://github.com/icedman/dash-animator

It works with Dash-to-Dock with all its nice features.

There is no published extension yet. But you can test with > git clone and the make install.
