### ISSUE TITLE
Feature request: move to side

### ISSUE THREAD

**Issue by bquast** [icedman/dash2dock-lite#30]
Hi, thank you for the great extension. I really love it.

Webpages and documents are mostly portrait, yet our screens are landscape. In order to make best use of the screen, having the dock on the side (the space almost always filled with blank in pages and text editors) is really useful. That way you can see as much as possible of the portrait website or document.

Ubuntu does this as well.

The old dash to dock might have some code that could be used for this:

https://github.com/micheleg/dash-to-dock/blob/master/docking.js

**Comment by icedman** [comment]
Thank you for your suggestion. I do use the vertical dock on the mac. This is in the works.

I do have the dash-to-dock code and refer to it and even have an extension that animates dash-to-dock with vertical layouts:

http://github.com/icedman/dash-animator  

This extension has less updates though and far in-between.. Also it does not support "show on all monitors"

**Comment by icedman** [comment]
Feature added as experimental. Enable experimental feature at the general pane.

**Comment by bquast** [comment]
Wow awesome 😎. I just landed from a long flight ✈️ to addis, going to
check this out right now.

I'll let you know if I notice anything.

If there is anything I particular I can look out for, let me know

**Comment by icedman** [comment]
This feature will be added on Anino Dock. https://github.com/icedman/anino-dock
-- Removed from Dash2Dock Lite. To make this extension lightweight again.
