### ISSUE TITLE
Feature Request:Minimize

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#32]
Feature Request: The ability to minimize and maximize clicking the icon.

**Comment by icedman** [comment]
click is currently reserved to the default click action of the dash.

update:
shift+scroll-up on icons => maximize/unmaximize (or show window if currently hidden)
shift+scroll-down on icons => minimize/unminimize (or unmaximize focused window if currently maximized)

scroll-up or down => cycles through all open windows

add CTRL to cycle/maximize/minimize only on the current workspace

this is takes time to get used to. but it feels natural. 
note: i'm using touch pad... scrollwheel might be opposite directions

**Comment by Ticklezz** [comment]
That is awesome. Will take some getting used to. I am on desktop and keyboard in a tray. For me click with mouse was more natural. Or what I am accustomed to doing with dash to dock currently. Still thank you for this.

**Comment by Ticklezz** [comment]
It takes 2 steps for it to minimize?

**Comment by icedman** [comment]
Yes. You'll have to press shift with scroll to minimize.

Scroll >> cycle windows
Shift+Scroll >> max/min windows
CTRL+Shift+Scroll >> max/min windows (current workspace)

I have these are preferences/tweaks so that we can remap. (I haven't implemented this yet though)

**Comment by icedman** [comment]
Note for maximize: If the window is not currently focused and raised.  It will regain focus and become raised first.  And you need the second swipe. 

This is currently necessary - for situations where you have multiple windows for one app - only the focused window gets maximized.

For minimize, there is no such limitation.

**Comment by Ticklezz** [comment]
Have you seen how simple dash to dock makes it? Are you against that? Or is it harder to achieve? I don't want to come off like a jerk. 1 clock of the mouse and it does both minimize and maximize or you can change it to do other functions.

**Comment by icedman** [comment]
This extension does not reimplement the dash but reusing the existing vanilla gnome shell dash - which uses the click to launch. It does not implement minimize/maximize.

So like I said earlier - Click is currently reserved to the default click action of the dash.

I'll look for a way to override this but until then we'll have to settle to mouse scroll.

**Comment by Ticklezz** [comment]
It's a great dock what you have made. If you ever were able to make it like dash to dock that would be amazing, Thank you for being so kind and helpful. I know you are doing this on your own time and I thank you for that.

**Comment by icedman** [comment]
Feature added.
New behavior. Click to minimize/unminimize. Press shift and click to maximize current focused window .

**Comment by Ticklezz** [comment]
Incredible stuff. Thank you for being open to implementing this feature.
