### ISSUE TITLE
option to opt out of top bar customization(?)

### ISSUE THREAD

**Issue by jrs-a** [icedman/dash2dock-lite#34]
I am currently using [transparent top bar extension](https://extensions.gnome.org/extension/3960/transparent-top-bar-adjustable-transparency/) and turns out, the functionality of the transparent top bar extension is being overridden by the top bar customization setting within dash2dock lite. I would love to have the option to enable/disable top bar customization within the dash2dock lite setting.

**Comment by icedman** [comment]
Feature added

**Comment by jrs-a** [comment]
Amazing work, thank you!

**Comment by Ticklezz** [comment]
This was great add as I use gradient top bar. Now if you added the gradient option.
