### ISSUE TITLE
Sometimes the dock disappears

### ISSUE THREAD

**Issue by pallebone** [icedman/dash2dock-lite#35]
Unsure how to troubleshoot this but sometimes the dock disappears and does not reappear if moving my mouse to the bottom of the screen. This seems to happen when the computer locks itself after a period of inactivity.

To resolve it I have to click the activities overview which then shows all my open app and the dock which I can then click on. This brings it back into focus and display again.

How can I troubleshoot why this happens?

Pete

**Comment by icedman** [comment]
Thanks for this report. 

If you're using the main branch, there is still a bug when using desktop icons extension (this has been fixed in the development branch)

If you're using the development branch, there is still (a bigger) bug where the autohide is not re-enabled after a desktop sleep or lock.

**Comment by pallebone** [comment]
I installed it off the gnome extension website so I presume I am using stable. I dont use desktop icons but do use conkey. Unsure if thats a similar issue. I do also use other extensions.

**Comment by icedman** [comment]
I've been doing house cleaning on the code - breaking some stuff in the processes. I won't update the extension on EGO until I've done tests. I might update the main branch though from time to time - when I feel the work is getting stable.

**Comment by pallebone** [comment]
Ok sounds good.

**Comment by pallebone** [comment]
Just so you know I still have this issue since the latest update but I did discover it has something to do with multi monitors, as I found that the dock actually will reappear on my first monitor if I move my mouse to the bottom of the second monitor. Once it appears it then works on monitor 1 as normal after that.
