### ISSUE TITLE
  What is the name of the icon theme used in this screenshot

### ISSUE THREAD

**Issue by Kodeekk** [icedman/dash2dock-lite#37]
What is the name of the icon theme used in [this screenshot](https://raw.githubusercontent.com/icedman/dash2dock-lite/main/screenshots/Screenshot%20from%202022-10-17%2021-33-29.png)

**Comment by prashantjain25** [comment]
![Screenshot from 2022-12-05 22-27-26](https://user-images.githubusercontent.com/5137282/205696479-bdc11496-924c-405e-bad3-db52bb65bc1a.png)
I know about these

**Comment by Kodeekk** [comment]
> ![Screenshot from 2022-12-05 22-27-26](https://user-images.githubusercontent.com/5137282/205696479-bdc11496-924c-405e-bad3-db52bb65bc1a.png) I know about these

So... What the name of this icon theme?

**Comment by prashantjain25** [comment]
use macosicons.com and get your own icons

**Comment by Kodeekk** [comment]
Thanks, but i need a ready-made icon pack

**Comment by icedman** [comment]
https://github.com/yeyushengfan258/Reversal-icon-theme
aur/reversal-icon-theme-git
