### ISSUE TITLE
Issue: Icons are shaking heavily on hovering items

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#38]
Its affected more and more when changing scroll sensitivity in dock settings.

**Comment by Ticklezz** [comment]
I have also seen this.

**Comment by icedman** [comment]
Is possible you could record the screen. If not, please upload a screenshot.
Possible cause: The icons now automatically scale down when they begin to overflow the screen.

**Comment by Ticklezz** [comment]
[Screencast from 12-06-2022 04:01:42 AM.webm](https://user-images.githubusercontent.com/113319295/205880731-ee9ad202-4e21-4d74-82e8-8d811c1e0497.webm)
  Here is a small clip.

**Comment by icedman** [comment]
I've pushed a fix both on main & development branches. Please help check if the shaking is gone on your settings. (on mine - it is no longer there). Thanks

**Comment by Ticklezz** [comment]
Will let you know when it goes through.

**Comment by Ticklezz** [comment]
The update has still yet to show up for me.

**Comment by Ticklezz** [comment]
Do I need to do a manual install? No update still.

**Comment by icedman** [comment]
I was not going upload to EGO until this was verified. I did however proceed with uploading this morning and now awaiting to the review.
