### ISSUE TITLE
Features Freeze

### ISSUE THREAD

**Issue by icedman** [icedman/dash2dock-lite#40]
The extension is getting bigger - it could no longer rightfully retain the word "Lite"

Hence, I'm freezing the addition of new features for Dash2Dock Lite.

This extension will be still be maintained however some features will be disabled/moved to **Anino Dock** (https://github.com/icedman/anino-dock)

Anino Dock starts with Release #20 of Dash2Dock Lite as base code. And new features requests should be directed to that project.

**Comment by Bananaman** [comment]
Good idea! Good luck with the project, I will be watching Anino Dock and might switch from D2D to it. :)

**Comment by icedman** [comment]
Features unfrozen.. With Gnome 45 requiring a major overhaul - I won't update AninoDock for a while.
