### ISSUE TITLE
Ions fit together

### ISSUE THREAD

**Issue by raphgilles** [icedman/dash2dock-lite#42]
Hello.

Everything worked like a charm, and after a reboot the icons was like on this screenshot. I desinstalled / reinstalled the extension. Restored the defauts settings of GNOME. But it seems to persist. What can I do ?

![Capture d’écran du 2022-12-27 07-38-08](https://user-images.githubusercontent.com/49836486/209623122-7ec75384-421c-458e-bab1-93c8db4d162c.png)

**Comment by icedman** [comment]
Try tweaks under settings and Increase 'spread'
What gnome version are you running?

**Comment by raphgilles** [comment]
I tried. It give some pixels more space, but the icons still lifted.

I’m using Ubuntu 22 with Gnome 42.5

**Comment by icedman** [comment]
I test on Ubuntu 22.04, Gnome 42.4. I don't have the issue.
Does that screenshot show the actual extent of the display?

**Comment by raphgilles** [comment]
Yes. I used the extension without problems for a week. And since this morning, it is displayed like this whereas when I turned off my computer yesterday it was working fine.

**Comment by icedman** [comment]
Ok. The update has code that will prevent icons from overflowing. I will adjust to allow exact fit. Please download and use release 20 for now

**Comment by icedman** [comment]
Or.. you could try panel mode.

**Comment by raphgilles** [comment]
I tried too. It still the same.

**Comment by icedman** [comment]
I could not re-create the bug. Could you tell  me a bit more info: dash2dock-lite version, screen size, screen scaling, wayland or xorg;
Thanks

**Comment by raphgilles** [comment]
I'm on a 3840x2160 screen scalled to 200%.
I'm using the v21 of D2DL.
I'm on X11.

For the output :
`Can't update stage views actor <overview>[<Gjs_ui_overview_OverviewActor>:0x5606dcf8d610] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_overviewControls_ControlsManager>:0x5606dd74c5f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesDisplay>:0x5606dd804aa0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesView>:0x5606dfb0b310] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspace_Workspace>:0x5606dd2ae250] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x5606df38f600] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x5606def1bc20] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x5606dfb13f60] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x5606dfb06ed0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StIcon>:0x5606dd819ee0] is on because it needs an allocation.
`

**Comment by raphgilles** [comment]
As you can see here, tt always return to this configuration.

https://user-images.githubusercontent.com/49836486/209652463-ba5736e8-43b8-41d2-9a4e-bc910607f928.mp4

**Comment by Ticklezz** [comment]
![Screenshot from 2022-12-27 08-58-18](https://user-images.githubusercontent.com/113319295/209694950-9b619827-972d-40fc-97a3-90ffd5b53ef2.png) They were never this close before with the spread at zero. Before this update they never touched with the same exact settings.

**Comment by Ticklezz** [comment]
![Screenshot from 2022-12-27 10-37-31](https://user-images.githubusercontent.com/113319295/209695371-c24cd86f-2193-45dc-9f55-371155160f98.png)
This is how my settings have been without the icons touching until now.

**Comment by raphgilles** [comment]
This is how it looks for me with the exact same settings.

![Capture d’écran du 2022-12-27 20-11-17](https://user-images.githubusercontent.com/49836486/209712165-4d747ee1-a9c4-4eb2-9c9b-f51560765d5a.png)

**Comment by icedman** [comment]
> As you can see here, tt always return to this configuration.
> 
>  2022-12-27.11-21-34.mp4

What is the name of your Desktop Icon extension. We had a similar problem with Desktop Icons NG before.

**Comment by icedman** [comment]
> I'm on a 3840x2160 screen scalled to 200%. I'm using the v21 of D2DL. I'm on X11.
> 
> For the output : `Can't update stage views actor <overview>[<Gjs_ui_overview_OverviewActor>:0x5606dcf8d610] is on because it needs an allocation. Can't update stage views actor <unnamed>[<Gjs_ui_overviewControls_ControlsManager>:0x5606dd74c5f0] is on because it needs an allocation. Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesDisplay>:0x5606dd804aa0] is on because it needs an allocation. Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_WorkspacesView>:0x5606dfb0b310] is on because it needs an allocation. Can't update stage views actor <unnamed>[<Gjs_ui_workspace_Workspace>:0x5606dd2ae250] is on because it needs an allocation. Can't update stage views actor <unnamed>[<ClutterActor>:0x5606df38f600] is on because it needs an allocation. Can't update stage views actor <unnamed>[<Gjs_ui_windowPreview_WindowPreview>:0x5606def1bc20] is on because it needs an allocation. Can't update stage views actor <unnamed>[<ClutterActor>:0x5606dfb13f60] is on because it needs an allocation. Can't update stage views actor <unnamed>[<ClutterClone>:0x5606dfb06ed0] is on because it needs an allocation. Can't update stage views actor <unnamed>[<StIcon>:0x5606dd819ee0] is on because it needs an allocation. `

Thanks. I will investigate.

**Comment by icedman** [comment]
@raphgilles 
It looks like a scaling bug. I deactivated the extension on the EGO site. Please reinstall with release 20 for now until I fix this. Thanks.

**Comment by raphgilles** [comment]
Fixed with [#5e4fcc0 ](https://github.com/icedman/dash2dock-lite/commit/5e4fcc0fe0b7948c8fa0d05fe893628dd98237e6).
Thanks !

**Comment by icedman** [comment]
@raphgilles  Thanks
