### ISSUE TITLE
Dock is not centered on secondary display

### ISSUE THREAD

**Issue by kevlawz** [icedman/dash2dock-lite#43]
I upgraded the extension, and the Dock is not centered on my secondary monitor. The Dock does center on laptop display. 
Monitor 1: Laptop 1080p (125% scaling)
Monitor 2: 27" 4K (150% scaling)
Primary Display set to Monitor 2

OS: Ubuntu 22.04.1 LTS x86_64 Wayland Gnome

![image](https://user-images.githubusercontent.com/32339789/209872870-c62ff0df-b55d-43a9-8dde-70c1f0e16778.png)

**Comment by icedman** [comment]
"setting external monitor as primary" . This could still be a problem. As the wrong scaling value could still be picked up.

**Comment by kevlawz** [comment]
The latest available version on the Gnome extensions website resolved the issue. I don't know if this commit could be rolled out to Gnome website that fast, so just providing this update in case another commit had already resolved the issue.

**Comment by icedman** [comment]
@kevlawz thanks. I did upload the fixes with the latest at the EGO.
