### ISSUE TITLE
Feature Request: dash2docklite and Anino

### ISSUE THREAD

**Issue by prashantjain25** [icedman/dash2dock-lite#44]
Suggested features that can be added:-

- The dock can add option for changing caption style for dock item labels
- Settings slider can show values changed for example radius of the dock can be represented with "px" changed on the slider itself
- Separator as a special item on the dock with no horizontal padding, which can be moved only through settings panel but not directly like other items.
- Plugins like fanout for any defined folder
- Shadows for special items like trash, mounted devices, fanout etc.
- Lock items from accidental movement

There is a good project for reference:-
[https://codepen.io/vihanga/pen/gOmXvRr](https://codepen.io/vihanga/pen/gOmXvRr)

**Comment by icedman** [comment]
Thanks for these. I was planning a fan out feature for Anino.

**Comment by icedman** [comment]
These new features will be considered under Anino. My aim for dash2dock lite is make it stable - fix reported bugs. So no new features for now.
