### ISSUE TITLE
Invisible icons after sleep mode

### ISSUE THREAD

**Issue by llaabbss3** [icedman/dash2dock-lite#45]
When waking after the sleep mode the dash doesn't show icons

**Comment by Swiiney** [comment]
Same here with latest Fedora. Icons and dock are invisibles after sleep. Labels are still visible.
Tried to disable / enable the extension with no luck.

Thanks for your help.

**Comment by icedman** [comment]
@llaabbss3 are you at Fedora as well? What gnome version are you using?
I'll probably install Fedora soon.

**Comment by Swiiney** [comment]
With version 27 it seems to be working.

**Comment by llaabbss3** [comment]
> With version 27 it seems to be working.

Yes, now everything is OK

**Comment by Swiiney** [comment]
The problem is back...
After disbling et enabling the dock it is working

**Comment by culinablaz** [comment]
Seems to be permanent on my machine (specs in the comment above)
