### ISSUE TITLE
Other Extension Animation don't work well

### ISSUE THREAD

**Issue by kaizen107** [icedman/dash2dock-lite#48]
With Dock Extensions i use Compiz Magic Effect Extension. The Animations are synced and work perfectly. In dash2dock lite the animation of other extension are not working in place is it the dock problem or what

**Comment by prashantjain25** [comment]
No issue with me using magic lamp Effect and dash2docklite simultaneous

**Comment by dude-shah** [comment]
Yeah it works fone but uts animation are not synced to the apps in dock it close with animation with flat downward animation ... Not to the app it opened from.

For instance my file explorere is at starting location of dock but the compiz magic animation doesn't close back to the file explorer but some other app in dock hope you get the idea

**Comment by icedman** [comment]
> Yeah it works fone but uts animation are not synced to the apps in dock it close with animation with flat downward animation ... Not to the app it opened from.
> 
> For instance my file explorere is at starting location of dock but the compiz magic animation doesn't close back to the file explorer but some other app in dock hope you get the idea

Could you upload a video so I could understand better. Thanks.

**Comment by Ticklezz** [comment]
[Screencast from 2023-01-09 15-01-24.webm](https://user-images.githubusercontent.com/113319295/211407753-6bc974c8-363b-422e-930f-12f19b881223.webm)
 I believe he is referring to this. Other docks the animation goes up and down with each app not from the center.

**Comment by dude-shah** [comment]
> [Screencast from 2023-01-09 15-01-24.webm](https://user-images.githubusercontent.com/113319295/211407753-6bc974c8-363b-422e-930f-12f19b881223.webm)
>  I believe he is referring to this. Other docks the animation goes up and down with each app not from the center. 

Yes that's the thing i was reying to explain ... 
Could you fix this issue, it ruins the experience

**Comment by icedman** [comment]
I installed this extension: https://github.com/hermes83/compiz-alike-magic-lamp-effect

And I see the problem. And it sound like it has a problem with dash-to-dock as well. I will spend a little time investigating its source code.

**Comment by dude-shah** [comment]
> I installed this extension: https://github.com/hermes83/compiz-alike-magic-lamp-effect
> 
> And I see the problem. And it sounds like it has a problem with dash-to-dock as well (from the comments) . I will spend a little time investigating its source code.
> 

When i use it with dash-to-dash it works fine

**Comment by icedman** [comment]
I pushed a fix for this on the main branch. Please check if this works already for you.
The lamp effect is not centered on the icon though.

I still had to edit the compiz effect extension. At extension.js. line 171

```
if (transformed_position && transformed_position[0]) {
   transformed_position[0] += dashElement.width/2;
   dashIcon = {x: transformed_position[0], y: monitor.y + monitor.height, width: 0, height: 0};
   return;
}
```

Perhaps you could post a request with compiz effect developer to add this single line:

```transformed_position[0] += dashElement.width/2;```

**Comment by icedman** [comment]
I might add these animation effects to Anino Dock :)
Thanks for posting this bug.

**Comment by icedman** [comment]
Lamp animations was added. But latest gnome version caused a lot of glitches. This feature is currently disabled until further notice.

**Comment by icedman** [comment]
Dash2Dock Animated should now be compatible with the Lamp Animation extension (by the original author)
