### ISSUE TITLE
Application button and dock in workspace overview

### ISSUE THREAD

**Issue by AlleNeri** [icedman/dash2dock-lite#5]
I use gnome as de on arch. I also use the just perfection extension that give to me possibility to show the applications button in the dock. But using dash2dock-lite it doesn't appear.
I can't also see the dock in the workspace overview.
Can you give me some help?

**Comment by icedman** [comment]
This extension purposely hid the apps button - as it behave differently from the other items on the dock.
App-icons branch was started to add it back. It may require re-thinking the animation code and would take a bit of time.

**Comment by icedman** [comment]
Added the apps button. Wont be animated though.
