### ISSUE TITLE
Dash2Dock Dock is overlapping with the slider dots in the applictaion menu

### ISSUE THREAD

**Issue by Royincog** [icedman/dash2dock-lite#50]
when i open application menu in ubuntu,  then the white dots is overlapping with the menu, please fix the issue. Would be much helpful!!
Thanks !!.
![Screenshot from 2023-01-20 10-34-52](https://user-images.githubusercontent.com/24631048/213621350-36b7e476-ce79-4a17-b530-6a07c495f75f.png)

**Comment by icedman** [comment]
Hi, do you mean the workspace switcher slider dots indicator?

**Comment by RTSAjwad** [comment]
The dash also overlaps items in the overview in general and doesn't make space for itself
[Screencast from 2023-11-14 15-55-52.webm](https://github.com/icedman/dash2dock-lite/assets/55037109/de0b899f-cde4-4e86-80b2-ff2de76a9ca5)

**Comment by icedman** [comment]
Recent version should have this fixed. Please update. Thanks.
