### ISSUE TITLE
Bug: Dock not visible when using two monitors

### ISSUE THREAD

**Issue by jgrecoarroyo** [icedman/dash2dock-lite#52]
When using this amazing extension on 2 monitors, the dock will only be visible on the secondary monitor.

If primary monitor selected on the settings as "preffered monitor", it will not be visible. Actually the labels will show on hover (see video below)

[Screencast from 2023-01-23 20-40-27.webm](https://user-images.githubusercontent.com/2805198/214133933-44929545-6023-4be4-b3f8-1e68fecc0026.webm)

Thank you for creating this amazing extension!
J

**Comment by SteeveMbr1** [comment]
I've got exactly the same issue.

**Comment by hlafaille** [comment]
Same issue here. Arch Linux, latest everything. For some reason this also made any application take forever to open.

**Comment by culinablaz** [comment]
Same issue using Ubuntu 22.04.2 LTS with 3 monitors.

**Comment by wbernadoque** [comment]
Same issue here, Ubuntu 22.04.2 LTS with 2 monitors, but when the dock its set on monitor of my laptop, works

**Comment by SolidCapo** [comment]
> dock is visible when primary monitor (integrated or external) is set on the left, but not if on the right of secondary.

WOAAHH!!! You're totally right! did the test and it works! but cant have it in that configuration, hope it works fine in the newest version for gnome 45 :S

**Comment by icedman** [comment]
Multi-monitor support has been added. Need testers though as I seldom connect my laptop to another monitor. Please help in testing. Thanks.
