### ISSUE TITLE
The `Preferred Monitor` option is switchable only 3-4 times

### ISSUE THREAD

**Issue by SteeveMbr1** [icedman/dash2dock-lite#53]
When I switch 3-4 times the `Preferred Monitor` option, i can switch it any more.

On the `Extension Manager` app, the drop-down option stay blocked.
![Screenshot from 2023-01-26 21-13-43](https://user-images.githubusercontent.com/15804282/214945280-30d30468-b14d-4325-a986-329a6bba979d.png)

And on the the `dconf` application I've got this message :
![Screenshot from 2023-01-26 21-13-54](https://user-images.githubusercontent.com/15804282/214945402-de8092a1-3b5d-4147-bf44-fe76fb4b197c.png)

**Comment by icedman** [comment]
Multi-monitor has been improved. Please re-open if this is issue is still present.
