### ISSUE TITLE
Does not play nice with Custom hot corners - Extended 

### ISSUE THREAD

**Issue by 0Raik** [icedman/dash2dock-lite#54]
I suspect the autohide/intellihide implementation can't work with **custom hot corners - extended** extension as it requires the bottom left and right corner to monitor and activate actions. Everything works with the usual **Dash to dock** but no matter what settings I'm changing for **dash2dock-lite** I can't activate the bottom corners. Really wish I could as its a deal-breaker.

Thank you so much for the time and effort for such an amazing extension. "**-lite**" in the name is an understatement. Kudos.

**Comment by icedman** [comment]
Please try the latest push on the main branch. And comment if this fixes it. Thanks.

**Comment by 0Raik** [comment]
Thank you so much!! It works but I also found a workaround with the current version at extensions.gnome.org 
I just have to disable the old Dash to dock and everything works as intended. Thanks for the patience and dedication. Will 5 stars the extension. Cheers!
