### ISSUE TITLE
Feature Req. : a way to fix it from showing too easily

### ISSUE THREAD

**Issue by P4prik4** [icedman/dash2dock-lite#55]
I like to do art in krita and anytime i draw near bottom of screen this pops up.  
i'd like just ability to set length of pixels that will pop up the dock.  
like maybe a percentage of bar length.  
and offset docker to left or right 
Or have a wheel setup in a corner

**Comment by icedman** [comment]
Please try enabling "Pressure sense". And disable "Peek icons".
You'll have to move the mouse "harder" at the bottom to show the dock.
