### ISSUE TITLE
While i open fullscreen proggrams dock fully disappears

### ISSUE THREAD

**Issue by DiamivaeBro** [icedman/dash2dock-lite#56]
Fedora 37 silverblue,gnome 43
Video of this bug:
https://imgur.com/a/24btOAP

**Comment by Charliecoop** [comment]
I get this too on Fedora 37 and also now on Fedora 38

**Comment by icedman** [comment]
Fixed.

**Comment by icedman** [comment]
Please update with the latest. And try it again.
