### ISSUE TITLE
Gnome 44?

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#58]
We getting gnome 44 support soon?

**Comment by icedman** [comment]
44 support has been added to metadatajson. 
I didn't upload to EGO yet though as I haven't installed gnome 44 yet

**Comment by Ticklezz** [comment]
> 44 support has been added to metadatajson. I didn't upload to EGO yet though as I haven't installed gnome 44 yet

I am here to tell you if it works if you want. My favorite extension. Was about update to opensuse tumbleweed. Gnome 44.

**Comment by icedman** [comment]
Arch linux finally pushed gnome 44. Hence  the update. Sorry for the wait. Please post issues.
