### ISSUE TITLE
Feature request: Custom individual icons

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#60]
Would it be possible to make it where one can easily change the icons to anything they choose? To be able to this individually on each app pinned to dock.

**Comment by icedman** [comment]
Possible. The clock and calendar icons does this but with custom draw and animation.
I will consider adding this.

**Comment by icedman** [comment]
Please check REadme to customize icons. The feature is still a little crude and needs testing.

**Comment by icedman** [comment]
Request fulfilled.
