### ISSUE TITLE
Error on "Permission denied for custom.css" when trying to disable the extensions

### ISSUE THREAD

**Issue by Windows7Pro2009** [icedman/dash2dock-lite#62]
I used Cubic to integrate the Dash2Dock Lite extension into my custom distro, and I'm not able to turn it off in the Extensions app (it is greyed out), saying that the permission is denied when trying to open the custom.css (which apparently for some reason is missing in the Dash2Dock extension folder). 

Specs:
OS: Debian 12 x64
DE: GNOME 43.4
RAM: 4GB
Disk: 50GB
(running on VMware Workstation Player 17 under Windows 11 Home build 22621.1992)

![image](https://github.com/icedman/dash2dock-lite/assets/76607426/5ad4525d-00ae-4a19-9846-986db95d35be)
(The error)

![image](https://github.com/icedman/dash2dock-lite/assets/76607426/d3b6defb-8a28-4c26-946e-7f548f0af96b)
(The "custom.css" file is not in the Dash2Dock extension folder; it wasn't even there in the downloaded zip file)

**Comment by icedman** [comment]
The latest version now saves custom.css to "/tmp" which is freely writeable.
Use g44 branch if you're still on gnome 44.
Main branch now has transistioned to gnome 45 which would be incompatible to to gnome 44.
