### ISSUE TITLE
Right side of dock becomes clickable and animation starts early

### ISSUE THREAD

**Issue by farellukas** [icedman/dash2dock-lite#63]
When I move my cursor slowly to the right side of the dock (in my case the applications icon), before even reaching the dock visually the rightmost icon already starts to animate and become clickable. It's as if there is a hidden icon next to the rightmost item. The same doesn't happen on the left side.

Here are screenshots of it:
![image](https://github.com/icedman/dash2dock-lite/assets/66014997/15e23b04-c8fa-42be-a73d-2172f1f850b2)
[left side perfectly fine]

![image](https://github.com/icedman/dash2dock-lite/assets/66014997/df3dd797-298f-4737-9b2c-8d1e48d2d3d7)
[right side starts early (applications icon already starts magnifying)]

**Comment by icedman** [comment]
This is being addressed as with issue #85
