### ISSUE TITLE
Invisible on primary monitor

### ISSUE THREAD

**Issue by SolidCapo** [icedman/dash2dock-lite#64]
If i activate it on secondary monitor, it works perfectly, but in primary it simply goes invisible, but the apps text on hover appears so it shows that it works, but for some reason is invisible.

![image](https://github.com/icedman/dash2dock-lite/assets/57196362/890e5ef7-c38f-44c4-b2e5-aa5beac3ff3c)

![image](https://github.com/icedman/dash2dock-lite/assets/57196362/db190726-0937-4ae9-b637-2a1feeed5781)

**Comment by Lija321** [comment]
I have the same issue

**Comment by Yannickbru** [comment]
I have the same issue too. Thank you for your work.
![Capture d’écran du 2023-08-15 11-26-05](https://github.com/icedman/dash2dock-lite/assets/74275713/272f6ffc-575c-4acd-b356-df900535c32a)

**Comment by FelipeTolentino** [comment]
Same!
![image](https://github.com/icedman/dash2dock-lite/assets/60939741/c9fcb583-8631-43ed-8154-85e9ca02ac0f)

**Comment by Varad-Codes** [comment]
I have the same error

**Comment by SolidCapo** [comment]
@gaelbilliard found the problem! this happens when the secondary monitor is on the left side! if you switch to the right, it works fine! did the test and it's true! but cant have it in that configuration, hope it works fine in the newest version for gnome 45 cause it seems that other versions won't have any more support :S

**Comment by diowil** [comment]
![image](https://github.com/icedman/dash2dock-lite/assets/15345064/1219a90a-4df2-4e8a-9660-96a865019bad)
Icons are only visible on the first monitor from the left (in my case icons are visible only on monitor 2). Dash2dock-lite seems to work on each monitor but icons are invisible (except first monitor from the left).

**Comment by SolidCapo** [comment]
> ![image](https://user-images.githubusercontent.com/15345064/278907589-1219a90a-4df2-4e8a-9660-96a865019bad.png) Icons are only visible on the first monitor from the left (in my case icons are visible only on monitor 2). Dash2dock-lite seems to work on each monitor but icons are invisible (except first monitor from the left).

Yeap, it's what all that have found this issue have discovered...but developers are also invisible :S i mean, haven't answered :S

**Comment by lucentxo** [comment]
Ridiculous this bug has existed for a year with no response whatsoever

**Comment by icedman** [comment]
Apology for the delayed fix. Dash2Dock now supports multi-monitor. 
Needs testing still.

**Comment by Lija321** [comment]
![Screenshot from 2024-03-15 19-41-25](https://github.com/icedman/dash2dock-lite/assets/31327026/1cc9c445-5764-46e4-a270-8b872f04e450)
I have a different problem. It is always displayed on the secondary monitor (most left one in my case). When its set the primary one it is still displayed on the left one buts hides when apps on the primary monitor are maximized

**Comment by icedman** [comment]
Multi-monitor support has been improved. Several bugs pertaining to multi-monitor have been addressed in the process. Please re-open a new issue for persisting bugs.

**Comment by SolidCapo** [comment]
Hope it works but for now i've switched to Plasma...so, good luck for those still there and test it :) thanks for doing it @icedman :)
