### ISSUE TITLE
Applications-grid icon on the left-end and trash icon on the right-end

### ISSUE THREAD

**Issue by YulBrinner90** [icedman/dash2dock-lite#66]
Hi icedman,

thanks for your awesome project. It would be perfect if it were possibile have the "applications-grid icon" on the left and the trash icon on the opposite right instead of the icons of the applicantions in execution. The result I would recreate is the same with dash-to-dock. From the left to the right:
1) Applications-grid icon
2) Favourite-applications icons
3) Icon of the applications in execution 
4) Trash icon 

I hope it will be possibile in the future. For now it is the only limit that block my migration from dash-to-dock to dash2dock-lite. Thanks in advance.

**Comment by icedman** [comment]
This feature for apps icon has been added. Trash icons and mount icons still not the proper location though.

**Comment by icedman** [comment]
Feature added. Apps Icon, Favorites, Running Apps, Mounted Devices, Downloads, Trash. With separators around running apps.
