### ISSUE TITLE
It needs Border Radius

### ISSUE THREAD

**Issue by itsdotnet** [icedman/dash2dock-lite#68]

**Comment by itsdotnet** [comment]
or i cannot found it

**Comment by schneik80** [comment]
![Screenshot from 2023-09-23 08-49-04](https://github.com/icedman/dash2dock-lite/assets/1480931/d76429e1-fce7-4fd1-aac9-e09ade9b5eb6)

the setting is on the appearance tab a few options down.

**Comment by itsdotnet** [comment]
Thanks
