### ISSUE TITLE
Lamp animation

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#69]
It works once and then maximizes windows and window is frozen. You cannot close and when you click dock icon it will minimize and reopen frozen. Not sure if it is conflicting with compiz extensions? The only way I could fix it  was super key and drag dash2dock-lite settings to another window and turn it off.

**Comment by icedman** [comment]
this feature has been temporarily remove. i will qait until the original author of lamp animations will fix the

**Comment by shayisnear** [comment]
is it back?

**Comment by icedman** [comment]
The lastest release should now be compatible with the Lamp Animation extension (by the original author).

**Comment by icedman** [comment]
This feature will be removed. Use the official one instead ... https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/
