### ISSUE TITLE
Jumpiness

### ISSUE THREAD

**Issue by icedman** [icedman/dash2dock-lite#72]
reddit ReadBearAK:

I'm seeing jumpiness with the dock on the left, with or without the animation enabled. Like the whole dock jumps up and down a few pixels as I move the mouse on/off the dock area, or just move the mouse around on the dock area. I disabled the animation to make sure it wasn't just the dock moving to accommodate the zooming of icons at the ends. It's more of a "jitter" kind of thing.

The autohiding also seems less reliable than Dash to Dock, which itself is not always perfect, but usually works. I have it set to always autohide, not dodge windows. Unless I do a pretty deliberate mouse over and mouse off movement, it can get stuck as visible and need the action to be repeated.

Happens pretty much every time if I slide off the dock slowly instead of quickly.

I've often had this trouble with both GTK and Qt panels on different Linux desktops, so that may not be easy to completely solve.

A funny thing I've noticed with an app of mine that uses GTK with Python to create a tray icon with menu: In order to get it to be able to update some of the menu items reliably, I ended up having to build a loop with a short delay to try to update the menu item and then check if it worked and try again a couple of times if it didn't.

I can't help but wonder if a similar hack might help with the issue of panels failing to notice that the mouse cursor is no longer over the panel area.

**Comment by Fexxix** [comment]
I also have the same issue with autohide, lemme know if you have found a fix.

**Comment by icedman** [comment]
The new reworked animation algorithm should have fixed this. There is still a tiny bit of shaking at end icons. Barely noticeable. Please file a new issue if there is still annoyingly shaking for you.
