### ISSUE TITLE
Autohide doesn't work on GNOME 45

### ISSUE THREAD

**Issue by morgan-greywolf** [icedman/dash2dock-lite#75]
Autohide doesn't work on GNOME 45.  Turning on Autohide Icons doesn't result in the dock hiding when overlapping a window or when an app is in fullscreen mode.

**Comment by icedman** [comment]
Do you have titling extensions, or probably desktop icons? Please list your extensions.

**Comment by icedman** [comment]
Release 50 is a major overhaul which includes improvements for autohide. Please check the latest at main branch as most autohide bugs have been addressed. Repost if the bug persists. Thanks
