### ISSUE TITLE
Clocks not working correctly on GNOME 45

### ISSUE THREAD

**Issue by morgan-greywolf** [icedman/dash2dock-lite#76]
When `gnome-clocks` is pinned to the dash, it doesn't correctly display the time on the icon if **Clock** is selected in the **Special Icons** tab on GNOME 45. 

Update:  the clock icon appears to display the _hour_ correctly, but the minute hand is not displayed and the seconds hand doesn't appear to move at all.

**Comment by icedman** [comment]
Sorry. The second hand IS the minute hand.... Currently displaying a second hand consumes too much CPU.
