### ISSUE TITLE
Trash not showing

### ISSUE THREAD

**Issue by egayghost** [icedman/dash2dock-lite#77]
I'm on arch GNOME 45, it seems like trash is not showing even though I already enabled it.

**Comment by Ticklezz** [comment]
I see I also cannot see trash.

**Comment by icedman** [comment]
PLease add under Others/Special icons

**Comment by Ticklezz** [comment]
> PLease add under Others/Special icons

You can do that and the trash icon does not appear.

**Comment by egayghost** [comment]
> PLease add under Others/Special icons

Still not showing

**Comment by joshagosh** [comment]
> > PLease add under Others/Special icons
> 
> You can do that and the trash icon does not appear.

Your suggestion doesn't work. Please look into the matter more than just providing your userbase with a generic respone. It's extremely annoying that I and others who use this software have to constantly refresh our gnome-shell or deal with not having a trash icon. If you need video proof your suggestion is not working I will gladly take it.

**Comment by Lija321** [comment]
> > > PLease add under Others/Special icons
> > 
> > You can do that and the trash icon does not appear.
> 
> Your suggestion doesn't work. Please look into the matter more than just providing your userbase with a generic respone. It's extremely annoying that I and others who use this software have to constantly refresh our gnome-shell or deal with not having a trash icon. If you need video proof your suggestion is not working I will gladly take it.

Bro he's making the extension for absolutely free... He probably has better things to do

**Comment by joshagosh** [comment]
> > > > PLease add under Others/Special icons
> > > 
> > > 
> > > You can do that and the trash icon does not appear.
> > 
> > 
> > Your suggestion doesn't work. Please look into the matter more than just providing your userbase with a generic respone. It's extremely annoying that I and others who use this software have to constantly refresh our gnome-shell or deal with not having a trash icon. If you need video proof your suggestion is not working I will gladly take it.
> 
> Bro he's making the extension for absolutely free... He probably has better things to do

Yes, I understand that, and the author has been giving the same suggestion over and over after people have stated the solution does not work. This has been an ongoing issue for a whole month, with the author giving everyone the same "suggestion" over and over, which is not working.

**Comment by Ticklezz** [comment]
> > > PLease add under Others/Special icons
> > 
> > 
> > You can do that and the trash icon does not appear.
> 
> Your suggestion doesn't work. Please look into the matter more than just providing your userbase with a generic respone. It's extremely annoying that I and others who use this software have to constantly refresh our gnome-shell or deal with not having a trash icon. If you need video proof your suggestion is not working I will gladly take it.

I think you should maybe just not use it if you can't be respectful to a man doing this for free. You have no right to treat him this way. He has a life and other things he has to do. Make your own damn one and make it perfect if it's so bad and this is so inconvenient for you. You come off as an entitled karen. The code is all here for you to fork it and fix what ever might be causing this issue. Or help him fix it. This isn't some fast food joint and you some customer crying your food is cold. This is the best dock for gnome and you come here showing disrespect. It's uncalled for and flat out rude. You will survive without a trash icon and you can access it from another area till he has the time to figure it out. You have no right at all to be calling him out like this ever. You honestly simply should just apologize for being so entitled. The fact you even felt the need to be this way is abhorrent to this community as a whole. It's disgusting behavior of someone who should understand what a great thing he as done and all of this for FREE. How dare you even behave this way at all. You should just be removed from github.

**Comment by Ticklezz** [comment]
> > > > > PLease add under Others/Special icons
> > > > 
> > > > 
> > > > You can do that and the trash icon does not appear.
> > > 
> > > 
> > > Your suggestion doesn't work. Please look into the matter more than just providing your userbase with a generic respone. It's extremely annoying that I and others who use this software have to constantly refresh our gnome-shell or deal with not having a trash icon. If you need video proof your suggestion is not working I will gladly take it.
> > 
> > 
> > Bro he's making the extension for absolutely free... He probably has better things to do
> 
> Yes, I understand that, and the author has been giving the same suggestion over and over after people have stated the solution does not work. This has been an ongoing issue for a whole month, with the author giving everyone the same "suggestion" over and over, which is not working.

![Screenshot 2023-11-22 at 12-06-23 joshagosh](https://github.com/icedman/dash2dock-lite/assets/113319295/5a6f202b-99b1-4609-af39-a784b499fcef)
 You have contributed nothing to this community and act like this? 100% uncalled for. Grow up and do better.

**Comment by Ticklezz** [comment]
@icedman I apologize for this pathetic behavior from this person. It's disgusting of them. What you have created is amazing and do not let some loser detract from that with petty childish comments.

**Comment by icedman** [comment]
Trash icon has been fixed. Release 50 at EGO
