### ISSUE TITLE
Autohide not working with secondary windows

### ISSUE THREAD

**Issue by RTSAjwad** [icedman/dash2dock-lite#78]
[Screencast from 2023-11-14 11-05-39.webm](https://github.com/icedman/dash2dock-lite/assets/55037109/25e57ef9-93dc-4ef3-89d4-e8a8c26c7af5)

Main windows auto hides the dash but the one that spawns from it doesn't

**Comment by RTSAjwad** [comment]
Another thing here that is odd is the delay in icon movement when it reappears. Might write a separate issue for this

**Comment by icedman** [comment]
Release 50 is a major overhaul which includes improvements for autohide. Please check the latest at main branch as most autohide bugs have been addressed. Repost if the bug persists. Thanks
