### ISSUE TITLE
Autohide sometimes doesn't work with full screen applications

### ISSUE THREAD

**Issue by RTSAjwad** [icedman/dash2dock-lite#79]
[Screencast from 2023-11-14 11-08-13.webm](https://github.com/icedman/dash2dock-lite/assets/55037109/f21af380-1281-4072-aaee-c99c51a76fd8)
Even when the app is full screen and the cursor isn't near the bottom, the dash shows itself.

**Comment by icedman** [comment]
Release 50 is a major overhaul which includes improvements for autohide. Please check the latest at main branch as most autohide bugs have been addressed. Repost if the bug persists. Thanks.
