### ISSUE TITLE
Breaks when GNOME display scale isn't 100%

### ISSUE THREAD

**Issue by Bananaman** [icedman/dash2dock-lite#8]
I tried it out and like your dock!

Unfortunately the whole dock is broken when GNOME Displays Scale is set to anything other than 100%.

The background becomes off-screen and the icons are super small.

**Comment by Bananaman** [comment]
BTW here is a cool message in case you missed it. Canonical (Ubuntu) want to hire you: https://www.reddit.com/r/gnome/comments/u421s6/comment/i4uvjis/

**Comment by icedman** [comment]
Could you post a screenshot. My display settings only allow 100% or 200% scale.

"Canonical (Ubuntu) want to hire you:" ... This was only an invitation to apply :)

**Comment by Bananaman** [comment]
Here is a video showing the issue:

https://user-images.githubusercontent.com/38923130/166116542-4deda079-c8eb-4f8a-b733-403d440e3530.mp4

My scale is 200% with 4K display:

![Screenshot from 2022-04-30 19-45-47](https://user-images.githubusercontent.com/38923130/166116556-a609bb46-1538-4fb5-b787-784b7f7a97d8.png)

If I set desktop scale to 100%, the dock looks more correct.

**Comment by icedman** [comment]
Latest version probably fixes these scaling problems. Please help verify as I have no fancy 4k monitors check.

**Comment by icedman** [comment]
Fixed under the development branch. This will be merged soon.

**Comment by Bananaman** [comment]
@icedman Thank you. I confirm that the development branch that you merged today fixes the scaling. Your extension is becoming cooler and cooler with every new update!

**Comment by Bananaman** [comment]
I can also confirm that your latest git master code of https://github.com/icedman/dash-animator scales properly too. Great job!

Just a curiousity: Is it possible to also move the running app indicators together with the icons? Both dash2dock-lite and dash animator look kinda weird because they leave the running app indicators behind on the dock.
