### ISSUE TITLE
BUG: (Unable to recreate with latest version) Dash is every so slightly transparent even when

### ISSUE THREAD

**Issue by RTSAjwad** [icedman/dash2dock-lite#80]
![Screenshot from 2023-11-14 16-09-34](https://github.com/icedman/dash2dock-lite/assets/55037109/bd1a645a-b28a-4793-bfaa-ed9efbc978d0)
![Screenshot from 2023-11-14 16-10-08](https://github.com/icedman/dash2dock-lite/assets/55037109/64d474f1-eb48-4214-92c0-c65ff38e3a7d)

First picture shows how background color is supposed to be opaque but second picture shows how there is slight transparency (you might have to zoom in).

**Comment by icedman** [comment]
What Gnome version do you have and what OS flavor?

**Comment by icedman** [comment]
code for gnome 42, 43, 44, 45, 46 has been unified. this problem could be from previous release. before the the major updates. pleaee reopen if the issue persist.  see the bug reporting section on readme.
