### ISSUE TITLE
Indentation between panel and desktops, constantly resets.

### ISSUE THREAD

**Issue by Articmar** [icedman/dash2dock-lite#82]
When the extension is enabled, the indentation between the desktop display and the panel is normal: 
![Снимок экрана от 2023-12-13 15-06-13](https://github.com/icedman/dash2dock-lite/assets/118318866/3ff46059-42ad-4d70-ab83-8315708d3248)

But after a while, for no particular reason, this indentation is reset: 
![Снимок экрана от 2023-12-14 17-14-39](https://github.com/icedman/dash2dock-lite/assets/118318866/6a36c276-03e5-4b42-b084-79973a22aa72)

It happens all the time.

Fedora Linux 39 (Workstation Edition)
GNOME 45.2

**Comment by icedman** [comment]
I made a recent fix for this. Please test and feedback if you can. Thanks.

**Comment by Articmar** [comment]
> I made a recent fix for this. Please test and feedback if you can. Thanks.

It seems to be working fine now. Thank you.
