### ISSUE TITLE
dock blocks inputs on either side while its up on screen

### ISSUE THREAD

**Issue by Jetsmokin** [icedman/dash2dock-lite#85]
hey there, love the extension, but I'm having an issue where whenever I bring up the dock, I can't click anything along the bottom of the screen until the dock hides again, even though the dock is only 5 apps in the middle of the screen . Basically the "hitbox" of the dock behaves as if its in panel mode, so when I'm clicking open space along the bottom of the screen i have to wait for the dock to hide again. hopefully that makes sense. 

Im using Fedora 39 with GNOME 45 /w Wayland. Thanks.

**Comment by icedman** [comment]
Added some fix for this. Please check development branch - or download the latest at extensions.gnome.org.
