### ISSUE TITLE
App menu not working after update

### ISSUE THREAD

**Issue by imrahulsharmaa** [icedman/dash2dock-lite#87]
I am using fedora 39 everything was working perfectly but when i updated it now app menu isnt working and also its lagging.

**Comment by icedman** [comment]
Could you check the latest upload (release 44) and see if the lag and menu bug is fixed.
You could also pull the latest from the main branch to check.
 Thanks.

**Comment by imrahulsharmaa** [comment]
Now its working but lagging and also dock is now hiding too fast.

**Comment by icedman** [comment]
This extension has been updated to address the lag issue. New features have also been added. Prominently,  multi-monitor support.

**Comment by imrahulsharmaa** [comment]
Now working properly
