### ISSUE TITLE
Lag on debain 12 

### ISSUE THREAD

**Issue by Sycorlax** [icedman/dash2dock-lite#88]
When I do the overview, it shows me a weird view like this : 
![Screenshot from 2024-03-06 16-43-00](https://github.com/icedman/dash2dock-lite/assets/114692357/09ba6d70-8263-4598-b22a-d63bd2f95a54)
and this is the the view i want : 
![image](https://github.com/icedman/dash2dock-lite/assets/114692357/ed78f64d-f889-4ac7-bc66-1d82a67f98d4)

**Comment by icedman** [comment]
I've overhauled the extension to make it more efficient. Please try the latest on github.

**Comment by icedman** [comment]
The main branch has been updated again. It seems on Ubuntu there is still some lag. Please post your systems if the lag is still very noticeable.

Run ```top -d 0.5``` on the terminal and observe the CPU usage of gnome-shell during active animation. On my old XPS13 i5 6th gen - CPU is at around 50%.  On Ubuntu it is at around 70%.

Possible temporary fix - run lower quality icons (2x) and Low frame rate.

**Comment by icedman** [comment]
Note:
I test on Ubuntu, Arch Linux, Fedora 39 (openbox). I assume any lag in Fedora 39 is just because it is run virtualized.

**Comment by icedman** [comment]
Latest Debian in Boxes is still at Gnome 44.9. The latest source has been improved form Gnome 45.

If you are adventurous.. you can try:

```python ./rolldown.py```

This will transpile the latest code to work for Gnome 44. The output is at ./dist/extension.js. Copy to {extensions_path}/dash2dock-lite/extension.js.

Preferences don't work yet though.

**Comment by icedman** [comment]
down ported latest code to debian 12 - gnome g43. now pretty fast.
