### ISSUE TITLE
Feature Request: Add reset button

### ISSUE THREAD

**Issue by IsaacBighi** [icedman/dash2dock-lite#89]
The extension is bugged and I can't use it anymore, if you add a reset button it would be great. When I place the mouse over it the dash does not appear.

**Comment by icedman** [comment]
This happened to me a few times already. We need to find out why and when this happens.  Please post if you have any clue.

**Comment by hunter99507** [comment]
It does not work for me either. Where are the user config files located in ubuntu so i can delete them and restart?

**Comment by icedman** [comment]
Reset button added
