### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jeannekamikaze** [icedman/dash2dock-lite#9]
On a fresh install of OpenSUSE on AMD Ryzen 5 5600H, this extension draws ~20% CPU usage on a constant basis. The extension "Dash to Dock for COSMIC", on the other hand, works without any noticeable overhead.

**Comment by icedman** [comment]
Hi are you using the version from git?
Do you have auto hide, animations, other settings?
Thanks.

**Comment by jeannekamikaze** [comment]
Not really sure how to install an extension from git. But since you've already confirmed and fixed the bug, maybe I can install the add-on from the Gnome site again when the latest version is published? Thank you.
