### ISSUE TITLE
Wrong progam opens when clicked.

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#91]
[Screencast from 2024-03-11 19-51-23.webm](https://github.com/icedman/dash2dock-lite/assets/113319295/243bc430-feeb-4648-b87b-8f5dfe4af465)

Here is a clip of what is occurring.

**Comment by icedman** [comment]
Please try the development branch.

It is a semi overhaul. Featuring a ton of improvements. The overhaul is done to support multi-monitors and to address the "lag" bug.

This new version also has this bug. But it at least shows a tooltip on which app will open.  And I will prioritizing to fix this bug on the development branch.

**Comment by Ticklezz** [comment]
Thanks as always. I will try that and will patiently wait for any fixes and changes.
