### ISSUE TITLE
How to reset settings.

### ISSUE THREAD

**Issue by hunter99507** [icedman/dash2dock-lite#92]
I am running ubuntu and the latest version of dash2dock (45). It doesnt work anymore. The main thing is clicking on icons wont launch anything when i am at the desktop. The dock zooms just fine when hovering over but left and right click do nothing. Infact when i am at the desktop and right click on "firefox" from the dock it opens the default right click like i was on the desktop (new folder, new document, ect...)

Also where is the settings config file saved? I want to do a complete default install while deleting my config.

Thanks

**Comment by icedman** [comment]
Please try the development branch. It has a lot of improvements, and bug fixes including the wrong clicks. I will update the main branch soon.

You can download dconf-editor. Find dash2dock-lite and do a reset recursively.

**Comment by icedman** [comment]
I'll add a settings for icons spacing. I've already added setting for dock padding.

**Comment by hunter99507** [comment]
Thanks for the quick response. I'll look into it tomorrow morning

**Comment by hunter99507** [comment]
I just tried the dev branch and it still cant click when im on the desktop. In the video I left clicking and also right clicking.
[Screencast from 2024-03-13 16-31-32.webm](https://github.com/icedman/dash2dock-lite/assets/127459480/70027a95-e7c9-4a5b-836c-b1fe97926660)

**Comment by icedman** [comment]
Could you post your OS and Gnome versions.

I like your theme :)

**Comment by hunter99507** [comment]
I'm running the latest version of Ubuntu which I think is 24.04, and gnome 45. I am also running x11.

I'm not home now so I can't get logs at the moment.

Thanks! I like it too, very simplistic and the dock looks great too!!

**Comment by icedman** [comment]
This has been resolved with release 50.
