### ISSUE TITLE
BUG: GNOME 45: Wrong dock position

### ISSUE THREAD

**Issue by aoberek** [icedman/dash2dock-lite#94]
Im on Gnome 45.3/Ubuntu 24.04, this is happening to the extension when activated:

![image](https://github.com/icedman/dash2dock-lite/assets/162039807/f0d78f63-2f0d-4488-b882-5946b88f8eb5)

**Comment by icedman** [comment]
Is this on a secondary monitor? Are you using display scaling?

**Comment by aoberek** [comment]
This is the primary monitor and I'm not using display scaling.

**Comment by icedman** [comment]
I need some more details. Could you please send the log or stack trace. See the readme under Bug Reporting.

**Comment by aoberek** [comment]
I've recently changed my Ubuntu version to 23.04 due to other incompatibilities and issues, and as a result, I cannot reproduce the bug anymore. Currently, I'm on Gnome 44.3/Ubuntu 23.04. It seems the issue was tied to the previous environment, and the upgrade has inadvertently resolved the problem with the extension when activated.

**Comment by icedman** [comment]
We'll close this bug for now until someone else can reproduce this. I've also added a "reset" settings button that could potential fix compatible settings from previous versions.
