### ISSUE TITLE
Icons getting cut off.

### ISSUE THREAD

**Issue by Ticklezz** [icedman/dash2dock-lite#96]
When you open anything the icon is getting cut off on animation. 

[Screencast from 2024-03-19 22-49-36.webm](https://github.com/icedman/dash2dock-lite/assets/113319295/04c16722-e44e-4f5a-a61d-b3ad98a7cc74)

**Comment by icedman** [comment]
Render area has now been increased to accommodate certain settings.

**Comment by icedman** [comment]
Please re-open if you still have this issue.

**Comment by Ticklezz** [comment]
[Screencast from 2024-03-29 16-52-38.webm](https://github.com/icedman/dash2dock-lite/assets/113319295/f539b993-7696-43fc-8a9d-32cb7761b6bb)
 It's back again unless you use panel mode.

**Comment by Ticklezz** [comment]
[Screencast from 2024-03-29 16-52-38.webm](https://github.com/icedman/dash2dock-lite/assets/113319295/25599dbc-14ea-43e5-80af-f82345bc1e87)

 It's back again, unless you use panel mode.
