### ISSUE TITLE
TypeError: desktopApp is null (v46 from extensions.gnome.org)

### ISSUE THREAD

**Issue by bcrescimanno** [icedman/dash2dock-lite#97]
On startup, the extension shows as enabled; but, it does not function properly (no animations work, etc.) 

Any attempt to change settings or disable the extension shows an error in the Gnome Extensions Panel: `TypeError: desktopApp is null`

I haven't pulled down the code to start digging into this one yet; but, I thought I'd report it here in case others are seeing the issue.

**Comment by Ticklezz** [comment]
> On startup, the extension shows as enabled; but, it does not function properly (no animations work, etc.)
> 
> Any attempt to change settings or disable the extension shows an error in the Gnome Extensions Panel: `TypeError: desktopApp is null`
> 
> I haven't pulled down the code to start digging into this one yet; but, I thought I'd report it here in case others are seeing the issue.

I have also seen this.

**Comment by icedman** [comment]
Most likely the 'mounted devices' or the 'trash' icon is the culprit. Try pulling the latest code or disable the mounted icons for now.

**Comment by Ticklezz** [comment]
> Most likely the 'mounted devices' or the 'trash' icon is the culprit. Try pulling the latest code or disable the mounted icons for now.

Didn't have either.

**Comment by bcrescimanno** [comment]
I disabled both the mounted icons and the trash and it's working properly now. I'm not sure all of my settings are actually being respected; but, the error is gone.

**Comment by icedman** [comment]
I've update the main branch with some fixes for this. Please check when you can. Thanks.

**Comment by bcrescimanno** [comment]
Verified as fixed for me running at commit [17a6085](https://github.com/icedman/dash2dock-lite/commit/17a60859cb8e95b2803cba933d46ed8020823b37)
