### ISSUE TITLE
Not working in Gnome 46

### ISSUE THREAD

**Issue by debianmain1** [icedman/dash2dock-lite#98]
Just a note that this is not working in Gnome 46. Hoping it will soon. I can test if you want/need me to.

**Comment by icedman** [comment]
Development branch now supports Gnome 46. (for testing)

**Comment by bcrescimanno** [comment]
Pulled down the g46 branch and built on my side. Looking good so far. Would you prefer separate issues for anything I find or track all g46 issues here for now?

**Comment by icedman** [comment]
Tracking here would be fine.

**Comment by bcrescimanno** [comment]
Marked the three issues above as resolved as of the latest commits on the g46 branch.

**Comment by icedman** [comment]
Thank you for helping
